// Code generated by protogen-wasm. DO NOT EDIT.
// source: echo/v1/echo.proto (lang=swift)

import Foundation
import WasmRpc

/// Typed wasm-rpc client for `echo.v1.EchoService`.
public struct EchoServiceClient: Sendable {
    private let transport: any WasmRpcTransport

    public init(transport: any WasmRpcTransport) {
        self.transport = transport
    }

    public func echo(_ request: Echo_V1_EchoRequest) async throws -> Echo_V1_EchoResponse {
        let payload = try request.serializedData()
        let raw = try await transport.invoke(
            method: "echo.v1.EchoService/Echo",
            payload: payload
        )
        return try Echo_V1_EchoResponse(serializedBytes: raw)
    }

    public func reverse(_ request: Echo_V1_ReverseRequest) async throws -> Echo_V1_ReverseResponse {
        let payload = try request.serializedData()
        let raw = try await transport.invoke(
            method: "echo.v1.EchoService/Reverse",
            payload: payload
        )
        return try Echo_V1_ReverseResponse(serializedBytes: raw)
    }

}

