// Package codegen implements the per-language emitters for protogen-wasm.
package codegen

import (
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Generator emits bindings for one proto file in one target language.
type Generator func(p *protogen.Plugin, f *protogen.File) error

var Languages = map[string]Generator{
	"go":     genGo,
	"ts":     genTS,
	"dart":   genDart,
	"kotlin": genKotlin,
	"swift":  genSwift,
}

const header = "// Code generated by protogen-wasm. DO NOT EDIT."

// fullMethod renders the wire identifier: "pkg.vN.Service/Method".
func fullMethod(s *protogen.Service, m *protogen.Method) string {
	return string(s.Desc.FullName()) + "/" + string(m.Desc.Name())
}

func isStreaming(m *protogen.Method) bool {
	return m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer()
}

// isServerStream reports server-streaming (the only streaming shape
// wasm-rpc supports; client/bidi remain skipped).
func isServerStream(m *protogen.Method) bool {
	return m.Desc.IsStreamingServer() && !m.Desc.IsStreamingClient()
}

func svcHasServerStream(s *protogen.Service) bool {
	for _, m := range s.Methods {
		if isServerStream(m) {
			return true
		}
	}
	return false
}

// filePrefix is the proto path without extension ("echo/v1/echo").
func filePrefix(f *protogen.File) string {
	return strings.TrimSuffix(f.Desc.Path(), ".proto")
}

// lowerCamel converts Echo -> echo, DoThing -> doThing.
func lowerCamel(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// upperCamel converts snake/kebab file basenames: my_api -> MyApi.
func upperCamel(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// relImport computes the JS-style relative import from the generated
// file for fromFile to the pb module of dep (both rooted at the same
// out directory), e.g. sibling -> "./echo_pb.js".
func relImport(fromDir, depPath, suffix string) string {
	dep := strings.TrimSuffix(depPath, ".proto") + suffix
	rel := relPath(fromDir, dep)
	if !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel
}

func relPath(fromDir, to string) string {
	if fromDir == "." || fromDir == "" {
		return to
	}
	fromParts := strings.Split(fromDir, "/")
	toDir, base := path.Dir(to), path.Base(to)
	toParts := []string{}
	if toDir != "." {
		toParts = strings.Split(toDir, "/")
	}
	i := 0
	for i < len(fromParts) && i < len(toParts) && fromParts[i] == toParts[i] {
		i++
	}
	var b strings.Builder
	for range fromParts[i:] {
		b.WriteString("../")
	}
	for _, p := range toParts[i:] {
		b.WriteString(p + "/")
	}
	b.WriteString(base)
	return b.String()
}

// javaOuterClass mirrors protoc's implicit outer-class naming: the
// CamelCase file basename, with "OuterClass" appended when it collides
// with a top-level type or service in the file.
func javaOuterClass(f *protogen.File) string {
	if opts := f.Proto.GetOptions(); opts != nil && opts.GetJavaOuterClassname() != "" {
		return opts.GetJavaOuterClassname()
	}
	name := upperCamel(strings.TrimSuffix(path.Base(f.Desc.Path()), ".proto"))
	collides := func(n protoreflect.Name) bool { return string(n) == name }
	for i := 0; i < f.Desc.Messages().Len(); i++ {
		if collides(f.Desc.Messages().Get(i).Name()) {
			return name + "OuterClass"
		}
	}
	for i := 0; i < f.Desc.Enums().Len(); i++ {
		if collides(f.Desc.Enums().Get(i).Name()) {
			return name + "OuterClass"
		}
	}
	for i := 0; i < f.Desc.Services().Len(); i++ {
		if collides(f.Desc.Services().Get(i).Name()) {
			return name + "OuterClass"
		}
	}
	return name
}

// swiftTypeName mirrors swift-protobuf naming: package components are
// CamelCased and joined with underscores ("echo.v1" -> "Echo_V1_"),
// then the (possibly nested) message path is appended.
func swiftTypeName(md protoreflect.MessageDescriptor) string {
	var names []string
	for d := protoreflect.Descriptor(md); d != nil; d = d.Parent() {
		if _, ok := d.(protoreflect.FileDescriptor); ok {
			break
		}
		names = append([]string{string(d.Name())}, names...)
	}
	pkg := string(md.ParentFile().Package())
	var prefix strings.Builder
	if pkg != "" {
		for _, p := range strings.Split(pkg, ".") {
			prefix.WriteString(strings.ToUpper(p[:1]) + p[1:] + "_")
		}
	}
	return prefix.String() + strings.Join(names, ".")
}
