// Code generated by protogen-wasm. DO NOT EDIT.
// source: ticker/v1/ticker.proto (lang=swift)

import Foundation
import WasmRpc

/// Typed wasm-rpc client for `ticker.v1.TickerService`.
public struct TickerServiceClient: Sendable {
    private let transport: any WasmRpcStreamTransport

    public init(transport: any WasmRpcStreamTransport) {
        self.transport = transport
    }

    public func subscribe(_ request: Ticker_V1_SubscribeRequest) -> AsyncThrowingStream<Ticker_V1_SubscribeResponse, Error> {
        AsyncThrowingStream { continuation in
            let task = Task {
                do {
                    let payload = try request.serializedData()
                    for try await frame in transport.listen(
                        method: "ticker.v1.TickerService/Subscribe",
                        payload: payload
                    ) {
                        continuation.yield(try Ticker_V1_SubscribeResponse(serializedBytes: frame))
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

}

