// End-to-end: instantiates the combined test guest under Node, then
// drives it through the compiled TypeScript clients generated by
// protogen-wasm — exercising CopyBytesToGo, the router, proto
// round-trip, streams, cancellation, CopyBytesToJS, and standardized
// error rejection.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import assert from "node:assert/strict";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../..");

// Overridable for alternative toolchains (e.g. TinyGo: point
// WASM_EXEC_JS at tinygo's wasm_exec.js and WASM_MODULE at its build;
// set SKIP_PANIC=1 since TinyGo cannot recover() on wasm).
const wasmExec = process.env.WASM_EXEC_JS ?? join(here, "wasm_exec.js");
const wasmModule = process.env.WASM_MODULE ?? join(here, "app.wasm");
const skipPanic = process.env.SKIP_PANIC === "1";

await import(wasmExec); // assigns globalThis.Go

const ready = new Promise((resolve) => {
  globalThis.__wasmRPCReady = resolve;
});
const go = new Go();
const { instance } = await WebAssembly.instantiate(
  readFileSync(wasmModule),
  go.importObject,
);
void go.run(instance);
await ready;

const dist = join(root, "client/ts/dist");
const { WasmRpcTransport, WasmRpcError } = await import(join(dist, "src/client.js"));
const { EchoServiceClient } = await import(join(dist, "gen/echo/v1/echo_wasmrpc.pb.js"));
const { TickerServiceClient } = await import(join(dist, "gen/ticker/v1/ticker_wasmrpc.pb.js"));

const transport = new WasmRpcTransport(globalThis.wasmRPC);
const echo = new EchoServiceClient(transport);
const ticker = new TickerServiceClient(transport);

// 1. Introspection across both mounted services
assert.deepEqual(transport.methods().sort(), [
  "echo.v1.EchoService/Echo",
  "echo.v1.EchoService/Reverse",
  "ticker.v1.TickerService/Subscribe",
]);

// 2. Happy path with repeat
const r1 = await echo.echo({ message: "hyp", repeat: 3 });
assert.equal(r1.message, "hyphyphyp");
assert.ok(Number(r1.unixMillis) > 0);

// 3. Rune-safe reverse (multi-byte UTF-8 across the boundary)
const r2 = await echo.reverse({ message: "héllo🚀" });
assert.equal(r2.message, "🚀olléh");

// 4. Typed handler error -> rejected Promise with standardized payload
await assert.rejects(
  () => echo.echo({ message: "x", repeat: 5000 }),
  (e) => e instanceof WasmRpcError && e.code === "invalid_argument",
);

// 5. Unregistered method -> unimplemented
await assert.rejects(
  () => transport.invoke("nope.v1.Nope/Nope", new Uint8Array()),
  (e) => e instanceof WasmRpcError && e.code === "unimplemented",
);

// 6. Bad argument type -> invalid_argument (no crash)
await assert.rejects(
  () => globalThis.wasmRPC.invoke("echo.v1.EchoService/Echo", "not bytes"),
  (e) => e.code === "invalid_argument",
);

// 7. Server stream: async-iterate all frames through the generated client
{
  const seqs = [];
  for await (const tick of ticker.subscribe({ topic: "tick", count: 4 })) {
    assert.equal(tick.topic, "tick");
    seqs.push(tick.seq);
  }
  assert.deepEqual(seqs, [1, 2, 3, 4]);
}

// 8. Stream cancellation mid-flight
{
  const stream = ticker.subscribe({ topic: "c", count: 50 });
  const seen = [];
  for await (const tick of stream) {
    seen.push(tick.seq);
    if (seen.length === 2) stream.cancel();
  }
  assert.ok(seen.length >= 2 && seen.length < 50, `cancelled after ${seen.length}`);
}

// 9. Stream handler panic -> WasmRpcError(internal), module survives.
// TinyGo cannot recover() on wasm, so panic recovery only holds for
// big-Go modules; set SKIP_PANIC=1 when testing TinyGo builds.
if (!skipPanic) {
  await assert.rejects(
    (async () => {
      for await (const _ of ticker.subscribe({ topic: "explode" })) void _;
    })(),
    (e) => e instanceof WasmRpcError && e.code === "internal",
  );
}

// 10. Unary-vs-stream misuse is a typed error, not a hang
await assert.rejects(
  () => transport.invoke("ticker.v1.TickerService/Subscribe", new Uint8Array()),
  (e) => e instanceof WasmRpcError && e.code === "invalid_argument",
);
await assert.rejects(
  (async () => {
    for await (const _ of transport.listenRaw("echo.v1.EchoService/Echo", new Uint8Array())) void _;
  })(),
  (e) => e instanceof WasmRpcError && e.code === "invalid_argument",
);

// 11. Module still alive after all error paths
const r3 = await echo.echo({ message: "still alive" });
assert.equal(r3.message, "still alive");

console.log(skipPanic
  ? "E2E PASS: 10/10 assertions across the Wasm boundary (panic-recovery skipped: TinyGo)"
  : "E2E PASS: 11/11 assertions across the Wasm boundary (unary + streams)");
process.exit(0);
